# -*- coding: utf-8 -*-
"""Winter 2022 Data Science Intern Challenge

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XTh2HT5iLi8jhV8pgbE9vy16621KthX0

Importing Dataset
"""

from google.colab import drive
drive.mount('/content/drive')
!ls "/content/drive/My Drive"

import os
os.getcwd()

os.chdir('/content/drive/MyDrive')
os.getcwd()

import pandas as pd
dataset = pd.read_excel("/content/drive/MyDrive/2019WinterDataScienceInternChallengeDataSet.xlsx")
print(dataset)

"""Dataset information"""

dataset.info()

dataset.describe()

"""We note that the maximum order_amount (704000.000) is too high compared to the median order_amount (284.000)."""

import numpy as np
maxItem = dataset[(dataset['total_items']==2000)]
maxOrder = dataset[(dataset['order_amount']==704000)]

maxItem

"""We find that all 2000-sized transactions were made by the same user (user_id: 607) from the same shop (shop_id: 42), and that the order_amount is the same in all cases (704000). 
In addition, we find that on these days, all payments are made at exactly 4am by credit card.

Droping outlier
"""

dataset = dataset.drop(dataset[dataset['order_amount']== 704000].index)

len(dataset)

import matplotlib.pyplot as plt
figure, axe = plt.subplots()
axe.scatter(dataset['total_items'],dataset['order_amount'])
axe.set_xlabel('total items')
axe.set_ylabel('order amount')
plt.show()

"""The scatterplot is divided into 2 classes: 
customers who spent less than 20,000 and others who spent more than that amount.
"""

more = dataset[dataset['order_amount'] > 20000]
more

"""Most of the sneakers sold in the store (shop_id: 78) cost more than 20000."""

dataset = dataset.drop(dataset[dataset['order_amount'] > 20000].index)

len(dataset)

"""New AOV """

AOV = sum(dataset['order_amount'])/len(dataset['order_id'])
AOV

dataset.describe()